ALTER TYPE "AccountStatus" ADD VALUE IF NOT EXISTS 'DORMANT';
ALTER TYPE "AccountStatus" ADD VALUE IF NOT EXISTS 'PROBATION';
ALTER TYPE "AccountStatus" ADD VALUE IF NOT EXISTS 'CLOSED';

ALTER TYPE "CreditSource" ADD VALUE IF NOT EXISTS 'ACCOUNT_CLOSURE_REFUND';
