import Link from "next/link";
import { redirect } from "next/navigation";
import { BarChart3, BriefcaseBusiness, CircleDollarSign, ClipboardCheck, Landmark, ReceiptText, UsersRound } from "lucide-react";
import { createLeaveRequest, createPerformanceReview, recordBusinessExpense, reviewLeaveRequest } from "@/actions/business-management";
import { recordStaffSalary } from "@/actions/salaries";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatMoney } from "@/lib/accounts";
import { auth } from "@/lib/auth";
import { getBusinessManagementOverview } from "@/lib/business-management";
import { todayDateInputValue } from "@/lib/date-rules";
import { isAdminRole } from "@/lib/roles";
import { salaryMonthInputValue } from "@/lib/salary-periods";

export const dynamic = "force-dynamic";
const input = "h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-950 outline-none focus:border-green-600 focus:ring-2 focus:ring-green-100";

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string | number; detail: string; icon: typeof UsersRound }) {
  return <Card><CardContent className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold text-gray-950">{value}</p><p className="mt-1 text-xs text-gray-500">{detail}</p></div><span className="rounded-lg bg-lime-100 p-2 text-green-800"><Icon className="size-5" /></span></CardContent></Card>;
}

function Status({ value }: { value: string }) {
  const tone = value === "APPROVED" ? "bg-green-100 text-green-800" : value === "REJECTED" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800";
  return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${tone}`}>{value}</span>;
}

export default async function BusinessManagementPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string; salaryError?: string }> }) {
  const session = await auth();
  if (!session?.user || !isAdminRole(session.user.role)) redirect("/dashboard");
  const [data, params] = await Promise.all([getBusinessManagementOverview(), searchParams]);
  const today = todayDateInputValue();
  const month = salaryMonthInputValue();
  const staffOptions = data.staff.map(s => <option key={s.id} value={s.id}>{s.code} — {s.fullName}</option>);

  return <div className="space-y-8">
    <header className="rounded-2xl bg-gradient-to-br from-green-950 via-green-900 to-emerald-800 p-6 text-white shadow-lg sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-200">Integrated operations</p><h1 className="mt-2 text-3xl font-bold">Business Management</h1><p className="mt-2 max-w-3xl text-sm text-green-100">HR, payroll, accounting, and analytics use the same GLV staff, customer payment, salary, and expense records.</p></div><BriefcaseBusiness className="size-10 text-lime-300" /></div><nav className="mt-6 flex flex-wrap gap-2 text-sm">{[["people","People"],["payroll","Payroll"],["accounting","Accounting"],["analytics","Analytics"]].map(([id,label]) => <a key={id} className="rounded-full bg-white/10 px-4 py-2 hover:bg-white/20" href={`#${id}`}>{label}</a>)}</nav></header>
    {params.saved ? <p className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm font-medium text-green-800">Record saved successfully.</p> : null}
    {params.error || params.salaryError ? <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">The record was not saved. Check every required field and date, then try again.</p> : null}

    <section id="analytics" className="scroll-mt-24 space-y-4"><div><h2 className="text-xl font-bold text-gray-950">Business analytics</h2><p className="text-sm text-gray-600">Current month financial and workforce position.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active staff" value={data.activeStaffCount} detail={`${data.pendingLeave} leave pending`} icon={UsersRound}/><Metric label="Revenue this month" value={formatMoney(data.monthlyRevenue)} detail="Customer payments recorded" icon={BarChart3}/><Metric label="Payroll paid" value={formatMoney(data.monthlyPayrollPaid)} detail={`${formatMoney(data.payrollOutstanding)} remaining commitment`} icon={CircleDollarSign}/><Metric label="Net cash this month" value={formatMoney(data.monthlyNetCash)} detail="Revenue less salary and expenses" icon={Landmark}/></div><div className="grid gap-4 md:grid-cols-3"><Metric label="Operating expenses" value={formatMoney(data.monthlyExpenses)} detail="Recorded this month" icon={ReceiptText}/><Metric label="All-time cash position" value={formatMoney(data.allTimeCashPosition)} detail="Collections less salary and expenses" icon={Landmark}/><Metric label="Average review" value={data.averageRating ? `${data.averageRating.toFixed(1)} / 5` : "No reviews"} detail="Latest performance records" icon={ClipboardCheck}/></div></section>

    <section id="people" className="scroll-mt-24 space-y-4"><div><h2 className="text-xl font-bold text-gray-950">People and HR</h2><p className="text-sm text-gray-600">Staff directory, leave decisions, and performance records.</p></div><div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Record leave request</CardTitle><CardDescription>Create and track a staff leave decision.</CardDescription></CardHeader><CardContent><form action={createLeaveRequest} className="grid gap-3 sm:grid-cols-2"><select name="staffId" required className={input}><option value="">Choose staff</option>{staffOptions}</select><select name="leaveType" required className={input}><option>Annual leave</option><option>Sick leave</option><option>Emergency leave</option><option>Unpaid leave</option></select><label className="text-xs font-medium text-gray-600">Start date<input name="startDate" type="date" required className={`${input} mt-1`}/></label><label className="text-xs font-medium text-gray-600">End date<input name="endDate" type="date" required className={`${input} mt-1`}/></label><textarea name="reason" placeholder="Reason or handover note" className={`${input} min-h-20 py-2 sm:col-span-2`}/><Button className="sm:col-span-2">Save leave request</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Performance review</CardTitle><CardDescription>Rate delivery and record coaching notes.</CardDescription></CardHeader><CardContent><form action={createPerformanceReview} className="grid gap-3 sm:grid-cols-2"><select name="staffId" required className={input}><option value="">Choose staff</option>{staffOptions}</select><select name="rating" required className={input}><option value="">Rating</option>{[5,4,3,2,1].map(n => <option key={n} value={n}>{n} / 5</option>)}</select><input name="reviewDate" type="date" max={today} defaultValue={today} required className={input}/><input name="strengths" placeholder="Strengths" className={input}/><input name="improvements" placeholder="Areas to improve" className={input}/><input name="notes" placeholder="Review notes" className={input}/><Button className="sm:col-span-2">Save performance review</Button></form></CardContent></Card>
    </div><Card><CardHeader><CardTitle>Leave requests</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr><th className="p-3 text-left">Staff</th><th className="p-3 text-left">Type</th><th className="p-3 text-left">Dates</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Decision</th></tr></thead><tbody>{data.recentLeave.map(row => <tr key={row.id} className="border-t"><td className="p-3"><b>{row.staff.code}</b><br/><span className="text-xs text-gray-500">{row.staff.fullName}</span></td><td className="p-3">{row.leaveType}</td><td className="p-3">{row.startDate.toLocaleDateString()} – {row.endDate.toLocaleDateString()}</td><td className="p-3"><Status value={row.status}/></td><td className="p-3">{row.status === "PENDING" ? <div className="flex gap-2"><form action={reviewLeaveRequest}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="APPROVED"/><Button size="sm">Approve</Button></form><form action={reviewLeaveRequest}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="REJECTED"/><Button size="sm" variant="destructive">Reject</Button></form></div> : "Completed"}</td></tr>)}</tbody></table>{data.recentLeave.length === 0 ? <p className="py-6 text-center text-gray-500">No leave requests yet.</p> : null}</div></CardContent></Card></section>

    <section id="payroll" className="scroll-mt-24 space-y-4"><div><h2 className="text-xl font-bold text-gray-950">Payroll</h2><p className="text-sm text-gray-600">Salary payments keep the existing staff SMS notification.</p></div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"><Card><CardHeader><CardTitle>Record salary payment</CardTitle></CardHeader><CardContent><form action={recordStaffSalary} className="grid gap-3"><input type="hidden" name="returnTo" value="business"/><select name="staffId" required className={input}><option value="">Choose staff</option>{data.staff.filter(s => s.active).map(s => <option key={s.id} value={s.id}>{s.code} — {s.fullName} ({formatMoney(s.monthlySalary)})</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Amount paid" className={input}/><label className="text-xs font-medium text-gray-600">Pay date<input name="paymentDate" type="date" max={today} defaultValue={today} required className={`${input} mt-1`}/></label><label className="text-xs font-medium text-gray-600">Salary month<input name="salaryMonth" type="month" max={month} defaultValue={month} required className={`${input} mt-1`}/></label><textarea name="notes" placeholder="Payment note" className={`${input} min-h-20 py-2`}/><Button>Record payment and notify staff</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Recent payroll</CardTitle><CardDescription>Salary payments recorded this month.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr><th className="p-3 text-left">Staff</th><th className="p-3 text-left">Salary month</th><th className="p-3 text-left">Paid</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{data.salaryPayments.map(row => <tr key={row.id} className="border-t"><td className="p-3"><b>{row.staff.code}</b> {row.staff.fullName}</td><td className="p-3">{row.salaryMonth.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</td><td className="p-3">{row.paymentDate.toLocaleDateString()}</td><td className="p-3 text-right font-semibold">{formatMoney(row.amount)}</td></tr>)}</tbody></table>{data.salaryPayments.length === 0 ? <p className="py-6 text-center text-gray-500">No salary payments this month.</p> : null}</div></CardContent></Card></div></section>

    <section id="accounting" className="scroll-mt-24 space-y-4"><div><h2 className="text-xl font-bold text-gray-950">Accounting</h2><p className="text-sm text-gray-600">The cashbook combines customer collections, payroll, and operating expenses.</p></div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"><Card><CardHeader><CardTitle>Record operating expense</CardTitle></CardHeader><CardContent><form action={recordBusinessExpense} className="grid gap-3"><input name="expenseDate" type="date" max={today} defaultValue={today} required className={input}/><select name="category" required className={input}><option value="">Choose category</option>{["Transport","Utilities","Office supplies","Marketing","Repairs","Communication","Other"].map(v => <option key={v}>{v}</option>)}</select><input name="description" required placeholder="What was paid for?" className={input}/><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Amount" className={input}/><select name="method" className={input}><option value="">Payment method</option>{["Cash","Mobile money","Bank transfer","Cheque"].map(v => <option key={v}>{v}</option>)}</select><input name="reference" placeholder="Reference (optional)" className={input}/><textarea name="notes" placeholder="Notes" className={`${input} min-h-20 py-2`}/><Button>Record expense</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Expense cashbook</CardTitle><CardDescription>Operating expenses for the current month.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Category</th><th className="p-3 text-left">Description</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{data.expenses.map(row => <tr key={row.id} className="border-t"><td className="p-3">{row.expenseDate.toLocaleDateString()}</td><td className="p-3">{row.category}</td><td className="p-3">{row.description}</td><td className="p-3 text-right font-semibold text-red-700">{formatMoney(row.amount)}</td></tr>)}</tbody></table>{data.expenses.length === 0 ? <p className="py-6 text-center text-gray-500">No operating expenses recorded this month.</p> : null}</div></CardContent></Card></div></section>
    <footer className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4 text-sm"><span className="text-gray-600">Financial reporting period starts {data.start.toLocaleDateString()}.</span><Link href="/reports" className="font-semibold text-green-700 hover:underline">Open detailed GLV reports →</Link></footer>
  </div>;
}
